### ISSUE TITLE
Spike: plan how to record user's progress

### ISSUE THREAD

**Issue by alodahl** [Techtonica/keyboard-shortcuts-practice#64]
Note: make pull requests to techtonica/keyboard-shortcuts-practice's 'backend' branch.

Find out the best way to record a user savepoint in Techtonica/keyboard-shortcuts-practice.

Document your new dev plan + user journey for how to access the data for a savepoint at the bottom of the project's ReadMe.md.

People who pick this up are going to have to research how the practice app progresses through its stages of difficulty so that they know which data to save once we have a user database.

**Comment by alodahl** [comment]
![userflow](https://user-images.githubusercontent.com/29131689/93008829-48637600-f52e-11ea-97d4-ac25373ad9b6.jpeg)

**Comment by vegetabill** [comment]
Hi @alodahl , The draft below covers the data model and auth. Please take a look and provide feedback, in particular the bolded open questions.

### DB Tables

#### `users` table
- `id`: string - will be an Auth0 identifier or an arbitrary value like "test" value for local development
- `last_login`: timestamp

Indexes needed: none

#### `user_answers` table
- `id`: integer sequence
- `user_id`: string (foreign key to `users.id`)
- `question_number`: integer
- `is_correct`: [boolean](https://sequelize.org/master/manual/model-basics.html#boolean)
-  `elapsed_time_ms`: integer
- created_at : timestamp (we don't need updated_at since this is immutable. this name can be [configured in the sequelize model](https://sequelize.org/master/manual/model-basics.html#timestamps) as we don't want the default camel case name)
 
Indexes needed:
- user_id, question_number
- user_id

*Open question: do we need `is_correct` or will we only store correct answers?* - I was wondering if we want to track % correct for the user.

### Authentication Setup
- *Open question: are we supporting guest usage or does the user need to be logged in?*
- Auth0 will provide a hosted signup/signin form (email/password) so we can delete issues related to building that UI
- Using the Auth0-endorsed express middleware, [express-openid-connect](https://www.npmjs.com/package/express-openid-connect), this will redirect the user to the login form if they are not logged in
- For local development, since developers will likely not have an Auth0 setup and there is not a simple way to stub it, I suggest we just have a sensible default, such as always logging in with user id "1" or "test"
- If the user is logged in and begins using the app, any API requests to save data can look at the request object and know the logged in user id 

### API endpoints
- `GET /user/answers/question/{questionNumber}` - returns the user's history of a question they have answered, a max of 3 previous records per unique question (for the timing UI)
- `POST /user/answers/question/{questionNumber}` - submit a (correct?) answer including its timing
- `GET /users/answers/last` - returns the most recently created answer record, which if the user wants to resume where they left off, would be one before where they should start
- `GET /user/answers` - bulk endpoint to get all the history in one request, which is similar to how the history code works now (??)
- `GET /questions` - (optional) move the public JSON file into the express server
- Note: `/login`, `/logout` will be provided by express-openid-connect and don't need any custom code

**Comment by alodahl** [comment]
This looks good!

I think guest usage should be fine.

Whatever feedback a user gets now should be available when they come back in another session, but we can break those things into separate issues do to later if need be.

**Comment by alodahl** [comment]
Also, I disagree that we don't need a login button. Would we want the user to be able to trigger the Auth0 login UI? And log out?  We just wouldn't need to design an input. Also, with a login button, the user has the option not to log in.  But we can discuss tomorrow =)

**Comment by vegetabill** [comment]
Mapped these reqs to the tickets on the board. Closing as done.
